package kz.company.shop.orders.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import kz.company.shop.orders.entity.*;

public record OrderDto(
        UUID id,
        String displayCode,
        Long userId,
        Long createdByUserId,
        String customerName,
        String customerEmail,
        OrderStatus status,
        PaymentStatus paymentStatus,
        PaymentMethod paymentMethod,
        BigDecimal cashPaymentAmount,
        BigDecimal cashlessPaymentAmount,
        CashlessPaymentType cashlessPaymentType,
        BigDecimal transferPaymentAmount,
        BigDecimal cardPaymentAmount,
        BigDecimal qrPaymentAmount,
        FulfillmentType fulfillmentType,
        String address,
        String contactPhone,
        String comment,
        String printComment,
        boolean wholesale,
        PriceTier priceTier,
        UUID priceSourceDocumentId,
        String priceSourceDocumentNumber,
        String priceSourceDocumentPriceType,
        boolean priceSourceDocumentDeleted,
        Long assemblyAssigneeId,
        String assemblyAssigneeName,
        Long checkingAssigneeId,
        String checkingAssigneeName,
        int assembledItems,
        int checkedItems,
        BigDecimal total,
        BigDecimal paidTotal,
        Instant createdAt,
        Instant reservationExpiresAt,
        List<OrderItemDto> items,
        Instant invoiceIssuedAt,
        UUID regularBuyerId,
        String regularBuyerName) {
    /** Compatibility overload for callers without a separate invoice recipient. */
    public OrderDto(
        UUID id,
        String displayCode,
        Long userId,
        Long createdByUserId,
        String customerName,
        String customerEmail,
        OrderStatus status,
        PaymentStatus paymentStatus,
        PaymentMethod paymentMethod,
        BigDecimal cashPaymentAmount,
        BigDecimal cashlessPaymentAmount,
        CashlessPaymentType cashlessPaymentType,
        BigDecimal transferPaymentAmount,
        BigDecimal cardPaymentAmount,
        BigDecimal qrPaymentAmount,
        FulfillmentType fulfillmentType,
        String address,
        String contactPhone,
        String comment,
        String printComment,
        boolean wholesale,
        PriceTier priceTier,
        UUID priceSourceDocumentId,
        String priceSourceDocumentNumber,
        String priceSourceDocumentPriceType,
        boolean priceSourceDocumentDeleted,
        Long assemblyAssigneeId,
        String assemblyAssigneeName,
        Long checkingAssigneeId,
        String checkingAssigneeName,
        int assembledItems,
        int checkedItems,
        BigDecimal total,
        BigDecimal paidTotal,
        Instant createdAt,
        Instant reservationExpiresAt,
        List<OrderItemDto> items,
        Instant invoiceIssuedAt) {
        this(id, displayCode, userId, createdByUserId, customerName, customerEmail, status, paymentStatus, paymentMethod, cashPaymentAmount, cashlessPaymentAmount, cashlessPaymentType, transferPaymentAmount, cardPaymentAmount, qrPaymentAmount, fulfillmentType, address, contactPhone, comment, printComment, wholesale, priceTier, priceSourceDocumentId, priceSourceDocumentNumber, priceSourceDocumentPriceType, priceSourceDocumentDeleted, assemblyAssigneeId, assemblyAssigneeName, checkingAssigneeId, checkingAssigneeName, assembledItems, checkedItems, total, paidTotal, createdAt, reservationExpiresAt, items, invoiceIssuedAt, null, null);
    }

    /** Compatibility overload for callers that predate invoice measurement metadata. */
    public OrderDto(
            UUID id,
            String displayCode,
            Long userId,
            Long createdByUserId,
            String customerName,
            String customerEmail,
            OrderStatus status,
            PaymentStatus paymentStatus,
            PaymentMethod paymentMethod,
            BigDecimal cashPaymentAmount,
            BigDecimal cashlessPaymentAmount,
            CashlessPaymentType cashlessPaymentType,
            BigDecimal transferPaymentAmount,
            BigDecimal cardPaymentAmount,
            BigDecimal qrPaymentAmount,
            FulfillmentType fulfillmentType,
            String address,
            String contactPhone,
            String comment,
            String printComment,
            boolean wholesale,
            PriceTier priceTier,
            UUID priceSourceDocumentId,
            String priceSourceDocumentNumber,
            String priceSourceDocumentPriceType,
            boolean priceSourceDocumentDeleted,
            Long assemblyAssigneeId,
            String assemblyAssigneeName,
            Long checkingAssigneeId,
            String checkingAssigneeName,
            int assembledItems,
            int checkedItems,
            BigDecimal total,
            BigDecimal paidTotal,
            Instant createdAt,
            Instant reservationExpiresAt,
            List<OrderItemDto> items) {
        this(
                id,
                displayCode,
                userId,
                createdByUserId,
                customerName,
                customerEmail,
                status,
                paymentStatus,
                paymentMethod,
                cashPaymentAmount,
                cashlessPaymentAmount,
                cashlessPaymentType,
                transferPaymentAmount,
                cardPaymentAmount,
                qrPaymentAmount,
                fulfillmentType,
                address,
                contactPhone,
                comment,
                printComment,
                wholesale,
                priceTier,
                priceSourceDocumentId,
                priceSourceDocumentNumber,
                priceSourceDocumentPriceType,
                priceSourceDocumentDeleted,
                assemblyAssigneeId,
                assemblyAssigneeName,
                checkingAssigneeId,
                checkingAssigneeName,
                assembledItems,
                checkedItems,
                total,
                paidTotal,
                createdAt,
                reservationExpiresAt,
                items,
                null);
    }

    /**
     * Compatibility overload for existing server-side callers that predate document price sources.
     */
    public OrderDto(
            UUID id,
            String displayCode,
            Long userId,
            Long createdByUserId,
            String customerName,
            String customerEmail,
            OrderStatus status,
            PaymentStatus paymentStatus,
            PaymentMethod paymentMethod,
            BigDecimal cashPaymentAmount,
            BigDecimal cashlessPaymentAmount,
            CashlessPaymentType cashlessPaymentType,
            BigDecimal transferPaymentAmount,
            BigDecimal cardPaymentAmount,
            BigDecimal qrPaymentAmount,
            FulfillmentType fulfillmentType,
            String address,
            String contactPhone,
            String comment,
            String printComment,
            boolean wholesale,
            PriceTier priceTier,
            Long assemblyAssigneeId,
            String assemblyAssigneeName,
            Long checkingAssigneeId,
            String checkingAssigneeName,
            int assembledItems,
            int checkedItems,
            BigDecimal total,
            BigDecimal paidTotal,
            Instant createdAt,
            List<OrderItemDto> items) {
        this(
                id,
                displayCode,
                userId,
                createdByUserId,
                customerName,
                customerEmail,
                status,
                paymentStatus,
                paymentMethod,
                cashPaymentAmount,
                cashlessPaymentAmount,
                cashlessPaymentType,
                transferPaymentAmount,
                cardPaymentAmount,
                qrPaymentAmount,
                fulfillmentType,
                address,
                contactPhone,
                comment,
                printComment,
                wholesale,
                priceTier,
                null,
                null,
                null,
                false,
                assemblyAssigneeId,
                assemblyAssigneeName,
                checkingAssigneeId,
                checkingAssigneeName,
                assembledItems,
                checkedItems,
                total,
                paidTotal,
                createdAt,
                null,
                items);
    }
}
